platnyedate =
            "SELECT "
                "`sdo`.`sdo_plat_uslugi_spisok`.`id` AS `ID`,"
                "`sdo`.`sdo_plat_uslugi_spisok`.`id_plat_uslugi` AS `PuID`,"
                "`sdo`.`sdo_plat_uslugi_sp`.`name_plat_usluga` AS `PuName`,"
                "`sdo`.`sdo_plat_uslugi_sp`.`price` AS `PuPrice`,"
                "`sdo`.`sdo_plat_uslugi`.`summ_plat_uslugi` AS `PuSumm`,"
                "`sdo`.`sdo_plat_uslugi`.`fio_plat` AS `PuFIOPlat`,"
                "FROM_UNIXTIME(`sdo`.`sdo_plat_uslugi`.`d_zapoln`) AS `PuDate`,"
                "`sdo`.`sdo_plat_uslugi`.`id_trup` AS `PuIDTrup`,"
                "CAST("
                    "CONCAT("
                        "lower(`sdo`.`sdo_trup4`.`fam`),"
                        "' ',"
                        "lower(`sdo`.`sdo_trup4`.`name`),"
                        "' ',"
                        "lower(`sdo`.`sdo_trup4`.`otch`)"
                    ") as CHAR(200) CHARSET utf8"
                ") AS `PuFIOTrup`,"
                "`sdo`.`sdo_otdel`.`name_otd` AS `puOtd`,"
                "`sdo`.`sdo_plat_uslugi`.`adres_plat` AS `PuAdrPlat` "
            "FROM "
                "`sdo`.`sdo_plat_uslugi_spisok` "
                "JOIN `sdo`.`sdo_plat_uslugi_sp` ON"
                    "`sdo`.`sdo_plat_uslugi_spisok`.`id_plat_usluga_sp` = `sdo`.`sdo_plat_uslugi_sp`.`id_sp`"
                "JOIN `sdo`.`sdo_plat_uslugi` ON"
                    "`sdo`.`sdo_plat_uslugi_spisok`.`id_plat_uslugi` = `sdo`.`sdo_plat_uslugi`.`id_usluga`"
                "JOIN `sdo`.`sdo_otdel` ON"
                    "`sdo`.`sdo_plat_uslugi`.`id_otd` = `sdo`.`sdo_otdel`.`id_otd`"
                "LEFT JOIN `sdo`.`sdo_trup4` ON"
                    "`sdo`.`sdo_plat_uslugi`.`id_trup` = `sdo`.`sdo_trup4`.`id_trup`"
            "WHERE "
                "("
                    "`sdo`.`sdo_plat_uslugi`.`d_zapoln` BETWEEN UNIX_TIMESTAMP((NOW() - INTERVAL 6 "
                        "MONTH)) and UNIX_TIMESTAMP(NOW()))"

otchet_platnyedate =
            "SELECT "
                "`sdo`.`platnyedate`.`id`, "
                "`sdo`.`platnyedate`.`PuID`, "
                "`sdo`.`platnyedate`.`PuName`, "
                "`sdo`.`platnyedate`.`PuPrice`, "
                "`sdo`.`platnyedate`.`PuSumm`, "
                "`sdo`.`platnyedate`.`PuFIOPlat`, "
                "`sdo`.`platnyedate`.`PuDate`, "
                "`sdo`.`platnyedate`.`PuIDTrup`, "
                "`sdo`.`platnyedate`.`PuFIOTrup`, "
                "`sdo`.`platnyedate`.`puOtd`, "
                "`sdo`.`platnyedate`.`PuAdrPlat`, "
                "`sdo`.`bars_svidet`.`Svidet_Num`, "
                "`sdo`.`bars_svidet`.`Status`, "
                "`sdo`.`bars_svidet`.`Kto_Vydal` "
            "FROM "
                "`sdo`.`platnyedate` "
            "LEFT JOIN "
                "`sdo`.`bars_svidet` ON "
                    "`sdo`.`platnyedate`.`PuFIOTrup` = `sdo`.`bars_svidet`.`Na_Kogo` "
            "WHERE "
                "("
                    "("
                        "(`sdo`.`platnyedate`.`PuDate`) BETWEEN STR_TO_DATE(
                            "CONCAT(
                                "YEAR(NOW() - INTERVAL 1 MONTH),"
                                "'-',
                                "MONTH(NOW() - INTERVAL 1 MONTH),
                                "'-',26),
                                "'%Y-%m-%d') AND STR_TO_DATE(
                                    "CONCAT(
                                        "YEAR(NOW()),
                                        "'-',
                                        "MONTH(NOW()),
                                        "'-',26),
                                        "'%Y-%m-%d')"
                    ")"
                ") "
            "ORDER BY "
                "`sdo`.`platnyedate`.`PuID`, "
                "`sdo`.`platnyedate`.`PuDate`;"

otchet_platnyedate_filtered =
            "SELECT "
                "`sdo`.`otchet_platnyedate`.`id`, "
                "`sdo`.`otchet_platnyedate`.`PuID`, "
                "`sdo`.`otchet_platnyedate`.`PuName`, "
                "`sdo`.`otchet_platnyedate`.`PuPrice`, "
                "`sdo`.`otchet_platnyedate`.`PuSumm`, "
                "`sdo`.`otchet_platnyedate`.`PuFIOPlat`, "
                "`sdo`.`otchet_platnyedate`.`PuDate`, "
                "`sdo`.`otchet_platnyedate`.`PuIDTrup`, "
                "`sdo`.`otchet_platnyedate`.`PuFIOTrup`, "
                "`sdo`.`otchet_platnyedate`.`puOtd`, "
                "`sdo`.`otchet_platnyedate`.`PuAdrPlat`, "
                "`sdo`.`otchet_platnyedate`.`Svidet_Num`, "
                "`sdo`.`otchet_platnyedate`.`Status`, "
                "`sdo`.`otchet_platnyedate`.`Kto_Vydal` "
            "FROM "
                "`sdo`.`otchet_platnyedate` "
            "GROUP BY "
                "`sdo`.`otchet_platnyedate`.`id` "
            "ORDER BY "
                "`sdo`.`otchet_platnyedate`.`PuID`, "
                "`sdo`.`otchet_platnyedate`.`PuDate`;"

without_platnye_date =
            "SELECT "
                "`sdo`.`bars_svidet`.`Data_Vydachi` AS `Data_Vydachi`, "
                "`sdo`.`bars_svidet`.`Svidet_Num` AS `Svidet_Num`, "
                "`sdo`.`bars_svidet`.`Na_Kogo` AS `Na_Kogo`, "
                "`sdo`.`bars_svidet`.`Status` AS `Status`, "
                "`sdo`.`bars_experts`.`OtdName` AS `OtdName`, "
                "`sdo`.`bars_svidet`.`Kto_Vydal` AS `Kto_Vydal` "
            "FROM "
                "`sdo`.`bars_svidet` "
                    "LEFT JOIN `sdo`.`platnyedate` ON "
                        "`sdo`.`bars_svidet`.`Na_Kogo` = CONVERT("
                            "`sdo`.`platnyedate`.`PuFIOTrup` USING utf8mb4)"
                    "LEFT JOIN `sdo`.`bars_experts` ON "
                        "`sdo`.`bars_svidet`.`Kto_Vydal` = `sdo`.`bars_experts`.`ExpertName`"
            "WHERE "
                "("
                    "("
                        "STR_TO_DATE("
                            "`sdo`.`bars_svidet`.`Data_Vydachi`, "
                            "'%d.%m.%Y'"
                        ") BETWEEN STR_TO_DATE("
                            "CONCAT("
                                "YEAR((NOW() - INTERVAL 1 MONTH)), "
                                "'-', "
                                "MONTH((NOW() - INTERVAL 1 MONTH)), "
                                "'-', "
                                "26), "
                                "'%Y-%m-%d') AND STR_TO_DATE("
                                    "CONCAT("
                                        "YEAR(NOW()), "
                                        "'-', "
                                        "MONTH(NOW()), "
                                        "'-', "
                                        "26), "
                                        "'%Y-%m-%d')"
                                    ") AND("
                                        "("
                                            "`sdo`.`platnyedate`.`PuFIOTrup` IS NULL"
                                        ") OR("
                                            "`sdo`.`platnyedate`.`PuFIOTrup` LIKE ''"
                                        ")"
                                    ")"
                                ")"

kosyak_podrobno =
            "SELECT "
                "`sdo`.`otchet_platnyedate`.`id` AS `id`, "
                "`sdo`.`otchet_platnyedate`.`PuID` AS `PuID`, "
                "`sdo`.`otchet_platnyedate`.`PuName` AS `PuName`, "
                "`sdo`.`otchet_platnyedate`.`PuPrice` AS `PuPrice`, "
                "`sdo`.`otchet_platnyedate`.`PuSumm` AS `PuSumm`, "
                "`sdo`.`otchet_platnyedate`.`PuFIOPlat` AS `PuFIOPlat`, "
                "`sdo`.`otchet_platnyedate`.`PuDate` AS `PuDate`, "
                "`sdo`.`otchet_platnyedate`.`PuIDTrup` AS `PuIDTrup`, "
                "`sdo`.`otchet_platnyedate`.`PuFIOTrup` AS `PuFIOTrup`, "
                "`sdo`.`otchet_platnyedate`.`puOtd` AS `puOtd`, "
                "`sdo`.`otchet_platnyedate`.`PuAdrPlat` AS `PuAdrPlat`, "
                "`sdo`.`otchet_platnyedate`.`Svidet_Num` AS `Svidet_Num`, "
                "`sdo`.`otchet_platnyedate`.`Status` AS `Status`, "
                "`sdo`.`otchet_platnyedate`.`Kto_Vydal` AS `Kto_Vydal` "
            "FROM "
                "`sdo`.`otchet_platnyedate` "
            "WHERE "
                "`sdo`.`otchet_platnyedate`.`id` IN("
                "SELECT "
                    "`sdo`.`otchet_platnyedate`.`id` "
                "FROM "
                    "`sdo`.`otchet_platnyedate` "
                "GROUP BY "
                    "`sdo`.`otchet_platnyedate`.`id` "
                "HAVING "
                    "(COUNT(0) > 1)"
            ") "
            "ORDER BY "
                "`sdo`.`otchet_platnyedate`.`id`"